import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

const bool themeMaterial3 = true;
const ThemeMode themeModeDefault = ThemeMode.dark;
// final String? themeFont = GoogleFonts.openSans().fontFamily;
final String themeFont = 'OpenSans';

class AppTheme {
  static ThemeData get lightTheme {
    return FlexThemeData.light(
      colors: const FlexSchemeColor(
        primary: Color(0xff0870b8),
        primaryContainer: Color(0xffeaf5fd),
        secondary: Color(0xffe92726),
        secondaryContainer: Color(0xffffffff),
        tertiary: Color(0xffdbdbdb),
        tertiaryContainer: Color(0xff95f0ff),
        appBarColor: Color(0xffffffff),
        error: Color(0xffb00020),
      ),
      appBarStyle: FlexAppBarStyle.background,
      transparentStatusBar: false,
      bottomAppBarElevation: 2.0,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 6,
        blendOnColors: false,
        useTextTheme: true,
        useM2StyleDividerInM3: true,
        adaptiveRemoveElevationTint: FlexAdaptive.excludeWebAndroidFuchsia(),
        adaptiveElevationShadowsBack: FlexAdaptive.excludeWebAndroidFuchsia(),
        adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
        defaultRadiusAdaptive: 10.0,
        adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
        elevatedButtonSecondarySchemeColor: SchemeColor.onSecondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.primary,
        segmentedButtonBorderSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderValueTinted: true,
        inputDecoratorSchemeColor: SchemeColor.primaryContainer,
        inputDecoratorIsFilled: false,
        inputDecoratorBorderSchemeColor: SchemeColor.primary,
        inputDecoratorUnfocusedBorderIsColored: false,
        inputDecoratorFocusedBorderWidth: 1.0,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
        inputCursorSchemeColor: SchemeColor.primary,
        fabUseShape: true,
        fabAlwaysCircular: true,
        fabSchemeColor: SchemeColor.primary,
        cardRadius: 14.0,
        popupMenuRadius: 6.0,
        popupMenuElevation: 3.0,
        dialogBackgroundSchemeColor: SchemeColor.background,
        dialogRadius: 10.0,
        datePickerDialogRadius: 10.0,
        timePickerDialogRadius: 10.0,
        drawerElevation: 1.0,
        drawerIndicatorSchemeColor: SchemeColor.primary,
        bottomSheetRadius: 18.0,
        bottomSheetElevation: 2.0,
        bottomSheetModalElevation: 4.0,
        bottomNavigationBarMutedUnselectedLabel: false,
        bottomNavigationBarMutedUnselectedIcon: false,
        menuRadius: 6.0,
        menuElevation: 3.0,
        menuBarRadius: 0.0,
        menuBarElevation: 1.0,
        menuBarShadowColor: Color(0x00000000),
        navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
        navigationBarMutedUnselectedLabel: false,
        navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationBarMutedUnselectedIcon: false,
        navigationBarIndicatorSchemeColor: SchemeColor.primary,
        navigationBarIndicatorOpacity: 1.00,
        navigationBarElevation: 1.0,
        navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
        navigationRailMutedUnselectedLabel: false,
        navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationRailMutedUnselectedIcon: false,
        navigationRailIndicatorSchemeColor: SchemeColor.primary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
      ),
      useMaterial3ErrorColors: true,
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: true,
      // To use the Playground font, add GoogleFonts package and uncomment
      fontFamily: themeFont,
    ).copyWith(
      splashFactory: NoSplash.splashFactory,
      splashColor: Colors.transparent,
      highlightColor: Colors.transparent,
      hoverColor: Colors.transparent,
      scaffoldBackgroundColor: Colors.white,
    );
  }

  static ThemeData get darkTheme {
    return FlexThemeData.dark(
      colors: const FlexSchemeColor(
        primary: Color(0xff9fc9ff),
        primaryContainer: Color(0xff00325b),
        secondary: Color(0xffffb59d),
        secondaryContainer: Color(0xff872100),
        tertiary: Color(0xff86d2e1),
        tertiaryContainer: Color(0xff004e59),
        appBarColor: Color(0xff872100),
        error: Color(0xffcf6679),
      ),
      surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
      blendLevel: 2,
      appBarStyle: FlexAppBarStyle.background,
      transparentStatusBar: false,
      bottomAppBarElevation: 2.0,
      subThemesData: const FlexSubThemesData(
        blendOnLevel: 8,
        useTextTheme: true,
        useM2StyleDividerInM3: true,
        adaptiveElevationShadowsBack: FlexAdaptive.all(),
        adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
        defaultRadiusAdaptive: 10.0,
        adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
        elevatedButtonSecondarySchemeColor: SchemeColor.onSecondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.primary,
        toggleButtonsBorderSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.primary,
        segmentedButtonBorderSchemeColor: SchemeColor.primary,
        unselectedToggleIsColored: true,
        sliderValueTinted: true,
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorIsFilled: false,
        inputDecoratorBackgroundAlpha: 22,
        inputDecoratorUnfocusedBorderIsColored: false,
        inputDecoratorFocusedBorderWidth: 1.0,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
        fabUseShape: true,
        fabAlwaysCircular: true,
        fabSchemeColor: SchemeColor.primary,
        cardRadius: 14.0,
        popupMenuRadius: 6.0,
        popupMenuElevation: 3.0,
        dialogBackgroundSchemeColor: SchemeColor.background,
        dialogRadius: 10.0,
        datePickerDialogRadius: 10.0,
        timePickerDialogRadius: 10.0,
        appBarScrolledUnderElevation: 3.0,
        drawerElevation: 1.0,
        drawerIndicatorSchemeColor: SchemeColor.primary,
        bottomSheetRadius: 18.0,
        bottomSheetElevation: 2.0,
        bottomSheetModalElevation: 4.0,
        bottomNavigationBarMutedUnselectedLabel: false,
        bottomNavigationBarMutedUnselectedIcon: false,
        menuRadius: 6.0,
        menuElevation: 3.0,
        menuBarRadius: 0.0,
        menuBarElevation: 1.0,
        menuBarShadowColor: Color(0x00000000),
        navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
        navigationBarMutedUnselectedLabel: false,
        navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationBarMutedUnselectedIcon: false,
        navigationBarIndicatorSchemeColor: SchemeColor.primary,
        navigationBarIndicatorOpacity: 1.00,
        navigationBarElevation: 1.0,
        navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
        navigationRailMutedUnselectedLabel: false,
        navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
        navigationRailMutedUnselectedIcon: false,
        navigationRailIndicatorSchemeColor: SchemeColor.primary,
        navigationRailIndicatorOpacity: 1.00,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
      ),
      useMaterial3ErrorColors: true,
      visualDensity: FlexColorScheme.comfortablePlatformDensity,
      useMaterial3: true,
      // To use the Playground font, add GoogleFonts package and uncomment
      fontFamily: themeFont,
    ).copyWith(
      splashFactory: NoSplash.splashFactory,
      splashColor: Colors.transparent,
      highlightColor: Colors.transparent,
      hoverColor: Colors.transparent,
      scaffoldBackgroundColor: Colors.black12,
    );
  }
}
